=== stevo9510/XmlDesignParadigms/Assignment5/music.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!-- Define Types Upfront -->
	
	<!-- Album ID number in the form JW#### where is # is a digit.  I.e. JW followed by 4 digits -->
	<xs:simpleType name="albumIdType">
		<xs:restriction base="xs:ID">
			<xs:pattern value="JW\d{4}"/>
		</xs:restriction>
	</xs:simpleType>
	
	<!-- The album category (New Orleans, Swing, Modern, Bebop) --> 
	<xs:simpleType name="categoryType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="New Orleans"/>
			<xs:enumeration value="Swing"/>
			<xs:enumeration value="Modern"/>
			<xs:enumeration value="Bebop"/>
		</xs:restriction>
	</xs:simpleType>
	
	<!-- Length Type, limited to format of (23):(59):(59) -->
	<xs:simpleType name="lengthType">
		<xs:restriction base="xs:string">
			<xs:pattern value="([01]\d|2[0123]):([012345]\d):([012345]\d)"/>
		</xs:restriction>
	</xs:simpleType>
	
	<!-- Define All Attributes --> 
	<xs:attribute name="albumID" type="albumIdType"/>
	<xs:attribute name="category" type="categoryType"/>
	<xs:attribute name="length" type="lengthType"/>

	<!-- Root Element.  Contains one or more albums -->
	<xs:element name="inventory">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="album" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<!-- Album element, stores information about each album.  Contains one or more artist, and category/albumID attributes -->
	<xs:element name="album">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="title"/>
				<xs:element ref="artist" minOccurs="1" maxOccurs="unbounded"/>
				<xs:element ref="tracks"/>
			</xs:sequence>
			<xs:attribute ref="category" use="required"/>
			<xs:attribute ref="albumID" use="required"/>
		</xs:complexType>
	</xs:element>
	
	<!-- Title and artist elements.  These can contain empty/whitespace per professor -->
	<xs:element name="title" type="xs:string"/>
	<xs:element name="artist" type="xs:string"/>
	
	<!-- Tracks element that contains one or more track elements and an optional length attribute -->
	<xs:element name="tracks">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="track" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute ref="length" use="optional"/>
		</xs:complexType>
	</xs:element>
	
	<!-- Track element that contains a optional length attribute. Element contains name of the individual album track. -->
	<xs:element name="track">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute ref="length" use="optional"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== stevo9510/XmlDesignParadigms/Assignment5/jw.xml
<inventory xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:noNamespaceSchemaLocation="music.xsd">
   <album category="Bebop" albumID="JW1234">
		<title>Foo</title>
		<artist>Bar</artist>
		<artist>Baz</artist>
		<artist></artist>
		<tracks length="12:00:22">
			<track length="00:22:11">First</track>
			<track length="23:15:11">Second</track>
			<track length="02:59:23">Third</track>
			<track length="00:00:00"></track>
		</tracks>
	</album>
	<album category="Modern" albumID="JW3333">
		<title>Meteora</title>
		<artist>Linkin Park</artist>
		<tracks>
			<track>No One's Listening</track>
			<track length="00:03:00">Numb</track>
		</tracks>
	</album>
</inventory>
