=== stevo9510/XmlDesignParadigms/Assignment10/XmlWeatherApplication/WebContent/WEB-INF/Weather.dtd
<!--  Weather DTD for Cities				-->

<!ELEMENT WEATHER (CITY)+>

<!--  CITY Element has HI, LOW, DESCRIPTION, and ICON Elements  -->
<!--  and a required NAME Attribute								-->
<!ELEMENT CITY (HI, LOW, DESCRIPTION, ICON)>
<!ATTLIST CITY NAME CDATA #REQUIRED>
<!ELEMENT HI (#PCDATA)>
<!ELEMENT LOW (#PCDATA)>
<!ELEMENT DESCRIPTION (#PCDATA)>
<!ELEMENT ICON EMPTY>

<!--  The ICON VALUE Attribute is restricted to one of six options  -->
<!ATTLIST ICON VALUE (SUNNY|PARTLYSUNNY|PARTLYCLOUDY|CLOUDY|RAIN|SNOW) #REQUIRED>

=== stevo9510/XmlDesignParadigms/Assignment10/XmlWeatherApplication/WebContent/WEB-INF/Weather.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE WEATHER SYSTEM "Weather.dtd">
<WEATHER>
	<CITY NAME="Hong Kong">
		<HI>87</HI>
		<LOW>78</LOW>
		<DESCRIPTION>Partly sunny.</DESCRIPTION>
		<ICON VALUE="PARTLYSUNNY"/>
	</CITY>
	<CITY NAME="London">
		<HI>65</HI>
		<LOW>60</LOW>
		<DESCRIPTION>Showers throughout the day.</DESCRIPTION>
		<ICON VALUE="RAIN"/>
	</CITY>
	<CITY NAME="New York">
		<HI>78</HI>
		<LOW>67</LOW>
		<DESCRIPTION>Sunny, hot and humid.</DESCRIPTION>
		<ICON VALUE="SUNNY"/>
	</CITY>
	<CITY NAME="San Fransisco">
		<HI>79</HI>
		<LOW>58</LOW>
		<DESCRIPTION>Partly cloudy.</DESCRIPTION>
		<ICON VALUE="PARTLYCLOUDY"/>	
	</CITY>
		<CITY NAME="Seattle">
		<HI>79</HI>
		<LOW>58</LOW>
		<DESCRIPTION>Raining.  Again.</DESCRIPTION>
		<ICON VALUE="RAIN"/>	
	</CITY>
</WEATHER>
